resources:
  - name: example_wo_repo
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration
      path: manishas-jfrog/example-write-output    # replace with your repository name
      branches:
        include: master

  - name: build_info_wo
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt  # replace with your Artifactory integration
      buildName: svc_build  # build name will be overwritten by pipeline name when used in Native steps
      buildNumber: 1  # build number will be overwritten by run number when used in Native steps

pipelines:
  - name: example_write_output_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: pipe-master.jfrog.info:8082/docker-local/myalpine  # replace with the image name you want
          dockerImageTag: ${run_number}
          inputResources:
            - name: example_wo_repo
          integrations:
            - name: demoArt # replace with your Artifactory integration
        execution:
          onStart:
            - add_run_variables commitSHA=res_example_wo_repo_commitSha
      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: docker-local  # replace if needed
          integrations:
            - name: demoArt # replace with your Artifactory integration
          inputSteps:
            - name: docker_build

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_wo
        execution:
          onSuccess:
            - write_output build_info_dbp "commitSHA=$commitSHA"
